name: "Build Wheels"

on:
  workflow_dispatch:

jobs:
  prepare-source:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare Source
      run: |
        git clone https://github.com/cupy/cupy-release-tools.git
        pushd cupy-release-tools
            git checkout "${GITHUB_REF}"
            git clone --recursive https://github.com/cupy/cupy.git
            pushd cupy
                git checkout "${GITHUB_REF}"
            popd
        popd
        tar cjf source.tar.gz cupy-release-tools

    - name: Upload Source
      uses: actions/upload-artifact@v2
      with:
        name: source
        path: source.tar.gz

  build:
    runs-on: self-hosted
    needs: [prepare-source]
    strategy:
      matrix:
        cuda: ["11.6-aarch64"]
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - name: Download Source
      uses: actions/download-artifact@v2
      with:
        name: source

    - name: Build
      run: |
        tar xf source.tar.gz
        cd cupy-release-tools
        #echo ./build.sh "${{ matrix.cuda }}" "${{ matrix.python }}" > "cupy-${{ matrix.cuda }}-${{ matrix.python }}.whl"
        ./build.sh "${{ matrix.cuda }}" "${{ matrix.python }}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: cupy-release-tools/cupy-*.whl
        if-no-files-found: error

  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Upload to GitHub Releases
      run: |
        echo TODO!
