name: "Build Wheels"

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Branch or Tag'
        required: true
      matrix_cuda:
        description: 'Matrix (CUDA)'
        required: true
        default: '["11.6-aarch64"]'
      matrix_python:
        description: 'Matrix (Python)'
        required: true
        default: '["3.7", "3.8", "3.9", "3.10"]'

jobs:
  prepare-source:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare Source
      run: |
        git clone https://github.com/cupy/cupy-release-tools.git
        pushd cupy-release-tools
            git checkout "${{ github.event.inputs.target }}"
            git clone --recursive https://github.com/cupy/cupy.git
            pushd cupy
                git checkout "${{ github.event.inputs.target }}"
            popd
        popd
        tar cjf source.tar.bz2 cupy-release-tools

    - name: Upload Source
      uses: actions/upload-artifact@v2
      with:
        name: source
        path: source.tar.bz2

  prepare-build:
    runs-on: self-hosted
    strategy:
      matrix:
        cuda: ${{ fromJSON(github.event.inputs.matrix_cuda) }}
    steps:
    - name: Prepare Build
      run: |
        echo Hi

  build:
    runs-on: self-hosted
    needs: [prepare-source, prepare-build]
    strategy:
      matrix:
        cuda: ${{ fromJSON(github.event.inputs.matrix_cuda) }}
        python: ${{ fromJSON(github.event.inputs.matrix_python) }}

    steps:
    - name: Download Source
      uses: actions/download-artifact@v2
      with:
        name: source

    - name: Build
      run: |
        tar xf source.tar.bz2
        cd cupy-release-tools
        #echo ./build.sh "${{ matrix.cuda }}" "${{ matrix.python }}" > "cupy-${{ matrix.cuda }}-${{ matrix.python }}.whl"
        ./build.sh "${{ matrix.cuda }}" "${{ matrix.python }}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: cupy-release-tools/cupy-*.whl
        if-no-files-found: error

  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Upload to GitHub Releases
      run: |
        echo TODO!
